import { defineSlotRecipe } from '@chakra-ui/react'

export const toastSlotRecipe = defineSlotRecipe({
  slots: [
    'root',
    'title',
    'description',
    'indicator',
    'closeTrigger',
    'actionTrigger',
  ],
  className: 'ds-toast',
  base: {
    root: {
      userSelect: 'none',
      width: 'full',
      display: 'flex',
      alignItems: 'flex-start',
      position: 'relative',
      gap: '3',
      py: '4',
      ps: '4',
      pe: '6',
      borderRadius: 'l3',
      translate: 'var(--x) var(--y)',
      scale: 'var(--scale)',
      zIndex: 'var(--z-index)',
      height: 'var(--height)',
      opacity: 'var(--opacity)',
      layerStyle: 'accent',
      colorPalette: 'secondary',
      willChange: 'translate, opacity, scale',
      transition:
        'translate 400ms, scale 400ms, opacity 400ms, height 400ms, box-shadow 200ms',
      transitionTimingFunction: 'cubic-bezier(0.21, 1.02, 0.73, 1)',
      _closed: {
        transition: 'translate 400ms, scale 400ms, opacity 200ms',
        transitionTimingFunction: 'cubic-bezier(0.06, 0.71, 0.55, 1)',
      },
      boxShadow: 'none',
      '--toast-trigger-bg': '{colors.colorPalette.highlight/10}',
      '--toast-border-color': '{colors.colorPalette.highlight/50}',
      '&[data-type=warning]': { colorPalette: 'orange' },
      '&[data-type=success]': { colorPalette: 'green' },
      '&[data-type=error]': { colorPalette: 'red' },
    },
    title: {
      textStyle: 'label',
      marginEnd: '2',
    },
    description: {
      fontFamily: 'heading',
      display: 'inline',
      textStyle: 'sm',
      opacity: '0.8',
    },
    indicator: {
      flexShrink: '0',
      boxSize: '5',
    },
    actionTrigger: {
      textStyle: 'sm',
      fontWeight: 'medium',
      height: '8',
      px: '3',
      mr: '2',
      cursor: 'pointer',
      borderRadius: 'l3',
      alignSelf: 'center',
      borderWidth: '1px',
      borderColor: 'var(--toast-border-color, inherit)',
      transition: 'background 200ms',
      _hover: {
        bg: 'var(--toast-trigger-bg)',
      },
      _active: {
        borderColor: 'colorPalette.highlight/30',
        bg: 'colorPalette.highlight/5 !important',
      },
    },
    closeTrigger: {
      position: 'absolute',
      top: '1',
      insetEnd: '1',
      padding: '1',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: '{currentColor/60}',
      borderRadius: 'l2',
      textStyle: 'md',
      transition: 'all 200ms',
      cursor: 'pointer',
      _hover: {
        color: '{currentColor}',
      },
      _icon: {
        boxSize: '1em',
      },
    },
  },
})
