import { defineSemanticTokens } from '@chakra-ui/react'

export const colors = defineSemanticTokens.colors({
  bg: {
    DEFAULT: { value: '{colors.primary.900}' },
    panel: { value: '{colors.primary.800}' },
    subtle: { value: '{colors.primary.950}' },
    muted: { value: '{colors.primary.700}' },
    emphasized: { value: '{colors.primary.600}' },
    error: { value: '{colors.red.950}' },
    warning: { value: '{colors.orange.950}' },
    success: { value: '{colors.green.950}' },
    info: { value: '{colors.secondary.900}' },
  },
  fg: {
    DEFAULT: { value: '{colors.white}' },
    emphasized: { value: '{colors.lilac}' },
    muted: { value: '{colors.deluge}' },
    subtle: { value: '{colors.twilight}' },
    primary: { value: '{colors.lilac}' },
    secondary: { value: '{colors.deluge}' },
    tertiary: { value: '{colors.twilight}' },
    error: { value: '{colors.red.400}' },
    warning: { value: '{colors.orange.300}' },
    success: { value: '{colors.green.300}' },
    info: { value: '{colors.lilac}' },
  },
  border: {
    DEFAULT: { value: '{colors.colorPalette.400}' },
    muted: { value: '{colors.colorPalette.600}' },
    highlight: { value: '{colors.colorPalette.50}' },
    error: { value: '{colors.red.400/70}' },
    warning: { value: '{colors.orange.400/70}' },
    success: { value: '{colors.green.400/70}' },
    info: { value: '{colors.primary.400/70}' },
  },
  primary: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.primary.50}' },
    subtle: { value: '{colors.primary.800}' },
    muted: { value: '{colors.primary.700}' },
    emphasized: { value: '{colors.primary.500}' },
    solid: { value: '{colors.primary.400}' },
    highlight: { value: '{colors.primary.300}' },
    focusRing: { value: '{colors.primary.200}' },
  },
  secondary: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.secondary.50}' },
    subtle: { value: '{colors.secondary.900}' },
    muted: { value: '{colors.secondary.800}' },
    emphasized: { value: '{colors.secondary.600}' },
    solid: { value: '{colors.secondary.500}' },
    highlight: { value: '{colors.secondary.300}' },
    focusRing: { value: '{colors.secondary.200}' },
  },
  gray: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.gray.300}' },
    subtle: { value: '{colors.gray.950}' },
    muted: { value: '{colors.gray.900}' },
    emphasized: { value: '{colors.gray.800}' },
    solid: { value: '{colors.gray.600}' },
    highlight: { value: '{colors.gray.500}' },
    focusRing: { value: '{colors.gray.500}' },
  },
  red: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.red.300}' },
    subtle: { value: '{colors.red.900}' },
    muted: { value: '{colors.red.800}' },
    emphasized: { value: '{colors.red.700}' },
    solid: { value: '{colors.red.600}' },
    highlight: { value: '{colors.red.500}' },
    focusRing: { value: '{colors.red.400}' },
  },
  orange: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.orange.300}' },
    subtle: { value: '{colors.orange.900}' },
    muted: { value: '{colors.orange.800}' },
    emphasized: { value: '{colors.orange.700}' },
    solid: { value: '{colors.orange.500}' },
    highlight: { value: '{colors.orange.400}' },
    focusRing: { value: '{colors.orange.300}' },
  },
  green: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.green.300}' },
    subtle: { value: '{colors.green.900}' },
    muted: { value: '{colors.green.800}' },
    emphasized: { value: '{colors.green.700}' },
    solid: { value: '{colors.green.600}' },
    highlight: { value: '{colors.green.500}' },
    focusRing: { value: '{colors.green.400}' },
  },
  blue: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.blue.300}' },
    subtle: { value: '{colors.blue.900}' },
    muted: { value: '{colors.blue.800}' },
    emphasized: { value: '{colors.blue.700}' },
    solid: { value: '{colors.blue.600}' },
    highlight: { value: '{colors.blue.500}' },
    focusRing: { value: '{colors.blue.500}' },
  },
  yellow: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.yellow.300}' },
    subtle: { value: '{colors.yellow.900}' },
    muted: { value: '{colors.yellow.800}' },
    emphasized: { value: '{colors.yellow.600}' },
    solid: { value: '{colors.yellow.400}' },
    highlight: { value: '{colors.yellow.300}' },
    focusRing: { value: '{colors.yellow.200}' },
  },
  teal: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.teal.300}' },
    subtle: { value: '{colors.teal.900}' },
    muted: { value: '{colors.teal.800}' },
    emphasized: { value: '{colors.teal.700}' },
    solid: { value: '{colors.teal.600}' },
    highlight: { value: '{colors.teal.500}' },
    focusRing: { value: '{colors.teal.500}' },
  },
  purple: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.purple.300}' },
    subtle: { value: '{colors.purple.900}' },
    muted: { value: '{colors.purple.800}' },
    emphasized: { value: '{colors.purple.700}' },
    solid: { value: '{colors.purple.600}' },
    highlight: { value: '{colors.purple.500}' },
    focusRing: { value: '{colors.purple.500}' },
  },
  pink: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.pink.300}' },
    subtle: { value: '{colors.pink.900}' },
    muted: { value: '{colors.pink.800}' },
    emphasized: { value: '{colors.pink.700}' },
    solid: { value: '{colors.pink.600}' },
    highlight: { value: '{colors.pink.500}' },
    focusRing: { value: '{colors.pink.500}' },
  },
  cyan: {
    contrast: { value: '{colors.white}' },
    fg: { value: '{colors.cyan.300}' },
    subtle: { value: '{colors.cyan.900}' },
    muted: { value: '{colors.cyan.800}' },
    emphasized: { value: '{colors.cyan.700}' },
    solid: { value: '{colors.cyan.600}' },
    highlight: { value: '{colors.cyan.500}' },
    focusRing: { value: '{colors.cyan.500}' },
  },
})
