import { useTranslation } from '@utils/i18n/useTranslation'
import { useMemo } from 'react'

export function useTimeline() {
  const { t } = useTranslation('page_home.timeline.items')

  return useMemo(
    () => [
      {
        src: '/images/home/timeline/design-system-bg.webp',
        srcParallax: '/images/home/timeline/design-system-parallax.webp',
        alt: t('design-system.title'),
        title: t('design-system.title'),
        desc: t('design-system.desc'),
        width: 3266,
        height: 2052,
      },
      {
        src: '/images/home/timeline/illuvium-portal-bg.webp',
        srcParallax: '/images/home/timeline/illuvium-portal-parallax.webp',
        alt: t('illuvium-portal.title'),
        title: t('illuvium-portal.title'),
        desc: t('illuvium-portal.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/overworld-bg.webp',
        srcParallax: '/images/home/timeline/overworld-parallax.webp',
        alt: t('overworld.title'),
        title: t('overworld.title'),
        desc: t('overworld.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/illuvidex-bg.webp',
        srcParallax: '/images/home/timeline/illuvidex-parallax.webp',
        alt: t('illuvidex.title'),
        title: t('illuvidex.title'),
        desc: t('illuvidex.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/account-web-bg.webp',
        srcParallax: '/images/home/timeline/account-web-parallax.webp',
        alt: t('account-web.title'),
        title: t('account-web.title'),
        desc: t('account-web.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/load-d1sk-bg.webp',
        srcParallax: '/images/home/timeline/load-d1sk-parallax.webp',
        alt: t('load-d1sk.title'),
        title: t('load-d1sk.title'),
        desc: t('load-d1sk.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/design-legacy-bg.webp',
        srcParallax: '/images/home/timeline/design-legacy-parallax.webp',
        alt: t('design-legacy.title'),
        title: t('design-legacy.title'),
        desc: t('design-legacy.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/staking-app-bg.webp',
        srcParallax: '/images/home/timeline/staking-app-parallax.webp',
        alt: t('staking-app.title'),
        title: t('staking-app.title'),
        desc: t('staking-app.desc'),
        width: 2940,
        height: 1844,
      },
      {
        src: '/images/home/timeline/ndapp-bg.webp',
        srcParallax: '/images/home/timeline/ndapp-parallax.webp',
        alt: t('ndapp.title'),
        title: t('ndapp.title'),
        desc: t('ndapp.desc'),
        width: 2000,
        height: 1250,
      },
      {
        src: '/images/home/timeline/wow-bg.webp',
        srcParallax: '/images/home/timeline/wow-parallax.webp',
        alt: t('wow.title'),
        title: t('wow.title'),
        desc: t('wow.desc'),
        width: 2000,
        height: 1250,
      },
      {
        src: '/images/home/timeline/apptite-bg.webp',
        srcParallax: '/images/home/timeline/apptite-parallax.webp',
        alt: t('apptite.title'),
        title: t('apptite.title'),
        desc: t('apptite.desc'),
        width: 2000,
        height: 1250,
      },
      {
        src: '/images/home/timeline/sharity-bg.webp',
        srcParallax: '/images/home/timeline/sharity-parallax.webp',
        alt: t('sharity.title'),
        title: t('sharity.title'),
        desc: t('sharity.desc'),
        width: 2000,
        height: 1250,
      },
      {
        src: '/images/home/timeline/itrack-bg.webp',
        srcParallax: '/images/home/timeline/itrack-parallax.webp',
        alt: t('itrack.title'),
        title: t('itrack.title'),
        desc: t('itrack.desc'),
        width: 2000,
        height: 1250,
      },
      {
        src: '/images/home/timeline/illsim-bg.webp',
        srcParallax: '/images/home/timeline/illsim-parallax.webp',
        alt: t('illsim.title'),
        title: t('illsim.title'),
        desc: t('illsim.desc'),
        width: 2000,
        height: 1250,
      },
    ],
    [t],
  )
}
